version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - cd src && npm install && npm install --prefix client
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js core
      - npm run build --prefix client
  post_build:
    commands:
      - echo Build completed on `date`
      - echo $CODEBUILD_SRC_DIR
artifacts:
  files:
    - src/server.js
    - src/client/build/**/*
    - package.json
    - node_modules/**/*
  discard-paths: yes
  # base-directory: $CODEBUILD_SRC_DIR
  name: amazing-$AWS_REGION
  